#!/bin/sh

echo "Running golangci-lint..."
cd "$(git rev-parse --show-toplevel)/server"
golangci-lint run
if [ $? -ne 0 ]; then
  echo "Lint errors. Commit blocked."
  exit 1
fi

echo "Lint passed."
exit 0
